name: vim

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-11
          - windows-2022
          # NOTE:
          # Use 'ubuntu-18.04' for now because using 'ubuntu-20.04' cause the following error
          #
          #   ERROR: helper/deps: Failed fetching deps: git clone --quiet --depth 1  'https://github.com/vim-jp/vital.vim' 'test/.deps/vital.vim'
          #   /usr/lib/git-core/git-remote-https: /tmp/.mount_vim6vy1Wm/usr/lib/x86_64-linux-gnu/libcrypt.so.1: version `XCRYPT_2.0' not found (required by /lib/x86_64-linux-gnu/libkrb5.so.26)
          #   /usr/lib/git-core/git-remote-https: /tmp/.mount_vim6vy1Wm/usr/lib/x86_64-linux-gnu/libcrypt.so.1: version `XCRYPT_2.0' not found (required by /lib/x86_64-linux-gnu/libroken.so.18)
          #   Error: Process completed with exit code 1.
          #
          # Somehow, this doesn't occured for Neovim.
          - ubuntu-18.04
        version:
          - head
          - v8.2.0235
          - v8.1.2424
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vim
        uses: thinca/action-setup-vim@v1
        id: vim
        with:
          vim_type: Vim
          vim_version: ${{ matrix.version }}
      - name: Download test runner
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: Prepare environment
        run: |
          git config --global user.name "github-action"
          git config --global user.email "github-action@example.com"
      - name: Run tests
        env:
          CI: 1
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
          # XXX:
          # Overwrite %TMP% to point a correct temp directory.
          # Note that %TMP% only affects value of 'tempname()' in Windows.
          # https://github.community/t5/GitHub-Actions/TEMP-is-broken-on-Windows/m-p/30432#M427
          TMP: 'C:\Users\runneradmin\AppData\Local\Temp'
        run: |
          ./vim-themis/bin/themis --reporter spec
